name: CI

on:
  push:
    branches: ["release"] # replace "main" with the default branch
  pull_request:
    branches: ["release"]
  workflow_dispatch:
      


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # uses lean standard action with all default input values
      - name: "run `lean-action` with only `lean4checker: true`"
        id: lean-action
        uses: leanprover/lean-action@v1
        with:
          auto-config: true

