name: CI

on:
  push:
    branches: ["release"] # replace "main" with the default branch
  pull_request:
    branches: ["release"]
  workflow_dispatch:
      


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "run `lean-action`"
        id: lean-action
        uses: leanprover/lean-action@v1
        with:
          auto-config: true
          use-github-cache: false

